# -*- coding: utf-8 -*-
"""Christian_Gonzalez_3_modelosS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14E2h_LYk_sPXkUVUfXsIlUEfbhJC6RuM

# Sistema Multiagente para Predicción del Rendimiento Estudiantil
Autor: Christian Gonzalez
"""

# ============================================================
# 1. INSTALACIÓN DE LIBRERÍAS NECESARIAS
# ============================================================
!pip install -q kagglehub
!pip install -q joblib
!pip install -q transformers
!pip install -q sentencepiece
!pip install -q accelerate

# ============================================================
# 2. IMPORTACIÓN DE LIBRERÍAS
# ============================================================
import os
import pandas as pd
import numpy as np
import kagglehub
import joblib
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from IPython.display import display
from google.colab import files
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

# ============================================================
# 3. AGENTE NORMALIZADOR
# ============================================================
class AgenteNormalizador:
    def __init__(self):
        self.scaler = StandardScaler()

    def descargar_dataset(self):
        path = kagglehub.dataset_download("rabieelkharoua/students-performance-dataset")
        print("Dataset descargado en:", path)
        print("Archivos encontrados:", os.listdir(path))
        return path

    def cargar_dataset(self, path):
        archivos_csv = [a for a in os.listdir(path) if a.endswith(".csv")]
        if not archivos_csv:
            raise FileNotFoundError("No se encontró ningún archivo CSV.")
        df = pd.read_csv(os.path.join(path, archivos_csv[0]))
        print("Dataset cargado correctamente. Filas y columnas:", df.shape)
        return df

    def explorar_dataset(self, df):
        print("Primeras filas del dataset:")
        display(df.head())
        print("\nInformación general del dataset:")
        df.info()
        print("\nValores nulos por columna:")
        print(df.isnull().sum())
        print("\nEstadísticas descriptivas:")
        display(df.describe())

    def graficar_distribucion_objetivo(self, df):
        fig, ax = plt.subplots(figsize=(8, 5))
        df["GradeClass"].value_counts().sort_index().plot(kind="bar", ax=ax)
        ax.set_title("Distribución de la variable objetivo GradeClass")
        ax.set_xlabel("Clase de rendimiento académico")
        ax.set_ylabel("Cantidad de estudiantes")
        plt.tight_layout()
        plt.show()
        plt.close(fig)

    def limpiar_y_normalizar(self, df):
        df = df.copy()
        if "GradeClass" not in df.columns:
            raise ValueError("No existe la columna objetivo GradeClass.")
        if "StudentID" in df.columns:
            df = df.drop("StudentID", axis=1)
        y = df["GradeClass"]
        X = df.drop("GradeClass", axis=1)
        X_norm = pd.DataFrame(self.scaler.fit_transform(X), columns=X.columns)
        X_norm["GradeClass"] = y.values
        return X_norm

# ============================================================
# 4. AGENTE ENTRENADOR
# ============================================================
class AgenteEntrenador:
    def __init__(self):
        self.modelos = {
            "Regresion Logistica": LogisticRegression(max_iter=1000),
            "Arbol de Decision":   DecisionTreeClassifier(random_state=42),
            "Random Forest":       RandomForestClassifier(random_state=42)
        }
        self.resultados = {}
        self.mejor_modelo = None
        self.nombre_mejor_modelo = None

    def preparar_datos(self, dataset):
        X = dataset.drop("GradeClass", axis=1)
        y = dataset["GradeClass"]
        try:
            return train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
        except ValueError:
            return train_test_split(X, y, test_size=0.2, random_state=42)

    def entrenar_modelos(self, X_train, X_test, y_train, y_test):
        for nombre, modelo in self.modelos.items():
            modelo.fit(X_train, y_train)
            pred = modelo.predict(X_test)
            self.resultados[nombre] = {
                "modelo":    modelo,
                "accuracy":  accuracy_score(y_test, pred),
                "precision": precision_score(y_test, pred, average="weighted", zero_division=0),
                "recall":    recall_score(y_test, pred, average="weighted", zero_division=0),
                "f1_score":  f1_score(y_test, pred, average="weighted", zero_division=0)
            }
        return self.resultados

    def seleccionar_mejor_modelo(self):
        self.nombre_mejor_modelo = max(self.resultados, key=lambda n: self.resultados[n]["f1_score"])
        self.mejor_modelo = self.resultados[self.nombre_mejor_modelo]["modelo"]
        return self.nombre_mejor_modelo, self.mejor_modelo

    def mostrar_metricas(self):
        rows = []
        for nombre, datos in self.resultados.items():
            rows.append({
                "Modelo":    nombre,
                "Accuracy":  datos["accuracy"],
                "Precision": datos["precision"],
                "Recall":    datos["recall"],
                "F1 Score":  datos["f1_score"]
            })
        return pd.DataFrame(rows)

# ============================================================
# 5. AGENTE COMUNICADOR
# ============================================================
class AgenteComunicador:
    def __init__(self):
        self.nombre_modelo_transformer = "google/flan-t5-small"
        self.tokenizer = None
        self.modelo = None
        try:
            self.tokenizer = AutoTokenizer.from_pretrained(self.nombre_modelo_transformer)
            self.modelo    = AutoModelForSeq2SeqLM.from_pretrained(self.nombre_modelo_transformer)
            print("Transformer cargado correctamente.")
        except Exception as e:
            print("No se pudo cargar el Transformer:", e)

    def generar_reporte_base(self, nombre_modelo, metricas_df):
        fila = metricas_df[metricas_df["Modelo"] == nombre_modelo].iloc[0]
        return (
            "El sistema multiagente desarrollado permite analizar el rendimiento "
            "estudiantil a partir de un dataset obtenido desde Kaggle.\n\n"
            "El Agente Normalizador se encargo de descargar el dataset, revisar "
            "valores nulos, eliminar columnas innecesarias como StudentID y normalizar "
            "las variables numericas mediante StandardScaler.\n\n"
            "El Agente Entrenador comparo tres modelos de clasificacion: Regresion "
            f"Logistica, Arbol de Decision y Random Forest. El mejor modelo fue {nombre_modelo}.\n\n"
            f"Metricas: Accuracy={fila['Accuracy']:.4f}, Precision={fila['Precision']:.4f}, "
            f"Recall={fila['Recall']:.4f}, F1 Score={fila['F1 Score']:.4f}.\n\n"
            "En conclusion, el modelo seleccionado presenta un rendimiento adecuado para "
            "clasificar el desempeno academico de los estudiantes."
        )

    def generar_reporte(self, nombre_modelo, metricas_df):
        if self.tokenizer is None or self.modelo is None:
            return self.generar_reporte_base(nombre_modelo, metricas_df)
        fila = metricas_df[metricas_df["Modelo"] == nombre_modelo].iloc[0]
        prompt = (
            "Write a short professional academic report in Spanish about a multi-agent system "
            "for student performance prediction. "
            f"Best model: {nombre_modelo}. "
            f"Accuracy: {fila['Accuracy']:.4f}. "
            f"F1 Score: {fila['F1 Score']:.4f}. "
            "Include conclusion."
        )
        try:
            entradas = self.tokenizer(prompt, return_tensors="pt", max_length=256, truncation=True)
            salida   = self.modelo.generate(**entradas, max_new_tokens=200, num_beams=2,
                                            do_sample=False, early_stopping=True)
            reporte  = self.tokenizer.decode(salida[0], skip_special_tokens=True)
            if len(reporte.strip()) < 100:
                return self.generar_reporte_base(nombre_modelo, metricas_df)
            return reporte
        except Exception as e:
            print("Error con Transformer, usando reporte base:", e)
            return self.generar_reporte_base(nombre_modelo, metricas_df)

# ============================================================
# 6. CLASE PARA GENERAR REPORTE EN TXT
# ============================================================

class ReporteTXT:
    """
    Genera el reporte final como archivo de texto plano (.txt).
    Sin dependencias externas, sin graficos, sin problemas de encoding.
    """

    def crear_txt(self, reporte_final, metricas_df, nombre_mejor_modelo):
        separador = "=" * 60
        lineas = []

        # Encabezado
        lineas.append(separador)
        lineas.append("REPORTE FINAL - SISTEMA MULTIAGENTE")
        lineas.append("Prediccion del Rendimiento Estudiantil")
        lineas.append(separador)
        lineas.append("")

        # Introduccion
        lineas.append("DESCRIPCION DEL SISTEMA")
        lineas.append("-" * 40)
        lineas.append(
            "Este reporte fue generado automaticamente por el sistema multiagente. "
            "El proyecto utiliza un Agente Normalizador, un Agente Entrenador "
            "y un Agente Comunicador basado en un modelo Transformer."
        )
        lineas.append("")

        # Metricas
        lineas.append("METRICAS OBTENIDAS")
        lineas.append("-" * 40)
        for _, fila in metricas_df.iterrows():
            lineas.append(
                f"Modelo    : {fila['Modelo']}\n"
                f"Accuracy  : {fila['Accuracy']:.4f}\n"
                f"Precision : {fila['Precision']:.4f}\n"
                f"Recall    : {fila['Recall']:.4f}\n"
                f"F1 Score  : {fila['F1 Score']:.4f}"
            )
            lineas.append("")

        # Mejor modelo
        lineas.append("-" * 40)
        lineas.append(f"MEJOR MODELO SELECCIONADO: {nombre_mejor_modelo}")
        lineas.append("-" * 40)
        lineas.append("")

        # Reporte del Transformer
        lineas.append("REPORTE GENERADO POR EL AGENTE COMUNICADOR")
        lineas.append("-" * 40)
        lineas.append(reporte_final)
        lineas.append("")
        lineas.append(separador)

        contenido = "\n".join(lineas)

        nombre_txt = "reporte_final.txt"
        with open(nombre_txt, "w", encoding="utf-8") as f:
            f.write(contenido)

        return nombre_txt

# ============================================================
# 7. EJECUCIÓN DEL SISTEMA MULTIAGENTE
# ============================================================

# --- Agente 1: Normalizador ---
agente1 = AgenteNormalizador()
path = agente1.descargar_dataset()
df_original = agente1.cargar_dataset(path)
agente1.explorar_dataset(df_original)
dataset_limpio = agente1.limpiar_y_normalizar(df_original)
dataset_limpio.to_csv("dataset_limpio.csv", index=False)
joblib.dump(agente1.scaler, "scaler.pkl")
print("Agente 1 finalizado: dataset limpio y scaler guardados.")

# --- Agente 2: Entrenador ---
agente2 = AgenteEntrenador()
X_train, X_test, y_train, y_test = agente2.preparar_datos(dataset_limpio)
agente2.entrenar_modelos(X_train, X_test, y_train, y_test)
nombre_mejor_modelo, mejor_modelo = agente2.seleccionar_mejor_modelo()
metricas_df = agente2.mostrar_metricas()
display(metricas_df)
joblib.dump(mejor_modelo, "modelo_final.pkl")
metricas_df.to_csv("metricas_modelos.csv", index=False)
print("Mejor modelo seleccionado:", nombre_mejor_modelo)
print("Agente 2 finalizado.")

# --- Agente 3: Comunicador ---
agente3 = AgenteComunicador()
reporte_final = agente3.generar_reporte(nombre_mejor_modelo, metricas_df)
print("\nREPORTE FINAL:")
print(reporte_final)

# --- Generación del TXT ---
reporte_txt = ReporteTXT()
archivo_txt = reporte_txt.crear_txt(reporte_final, metricas_df, nombre_mejor_modelo)
print("Reporte TXT generado correctamente:", archivo_txt)

# ============================================================
# 8. DESCARGA DE ARCHIVOS GENERADOS
# ============================================================
files.download(archivo_txt)
files.download("dataset_limpio.csv")
files.download("metricas_modelos.csv")
files.download("modelo_final.pkl")
files.download("scaler.pkl")
print("Todos los archivos fueron generados y descargados correctamente.")